### ISSUE TITLE
Hi, Please help me take a look

### ISSUE THREAD

**Issue by cspangge** [twilio-labs/plugin-queued-callbacks-and-voicemail#3]
I got this error when I run twilio flex:plugins:deploy --major --changelog "Change plugin to use the latest Flex plugin for the Twilio CLI" --description "Queued Callback and Voicemail Plugin"

(node:30265) UnhandledPromiseRejectionWarning: Error: Cannot find module 'craco-config-flex-plugin'
Require stack:
- /Users/pangge/twilio/voicemail/plugin-queued-callbacks-and-voicemail/craco.config.js
- /Users/pangge/.twilio-cli/node_modules/@craco/craco/lib/config.js
- /Users/pangge/.twilio-cli/node_modules/@craco/craco/scripts/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/pangge/twilio/voicemail/plugin-queued-callbacks-and-voicemail/craco.config.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:30265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Could not find build file. Did you run `npm run build` first?

**Comment by ktalebian** [comment]
@cspangge it looks like you have an older version of the `twilio` CLI. Please run the following:

```bash
# Install the latest version
twilio plugins:install @twilio-labs/plugin-flex@beta

# Now update your plugin
twilio flex:plugins:ugprade-plugin --beta --install

# Now re-run deploy command
```

**Comment by bermudezmt** [comment]
Hello @cspangge . As this has likely been addressed by our recent plugin upgrade, I am closing this issue. Please let us know if you are still having issues with this plugin.
