### ISSUE TITLE
Retry Later breaks the task that is re-queued.

### ISSUE THREAD

**Issue by Codewow** [twilio-labs/plugin-queued-callbacks-and-voicemail#65]
Currently on Flex UI 2.10.0.
Using the plugin version 1.1.0

1. Create the original task
2. Accept the task on Flex.
3. Click "Retry Later"
4. Accept/Click the new task assigned to you.
5. Get a blank flex page.
6. Notice that the task never goes away and must be deleted from Task Router manually to remove it.

The task flex UI is returning is WR1aece6863f1ae984e675290a1fdf2b09
But the Task in TaskRouter is actually WTf398575f999eb65d40583aed410f3394

When refreshing the final blank page, this error gets returned.

# Twilio Flex Error report
---

### LOG LINE
```
12/11/2024, 2:21:55 PM - DynamicComponent: An error has been detected inside the AgentDesktopView.Panel2 DynamicComponent

Original error:
"Cannot read properties of undefined (reading 'replace')"
```

### STACK TRACE
```
Error: An error has been detected inside DynamicComponent
    at new n (https://assets.flex.twilio.com/releases/flex-ui/2.10.0/twilio-flex.unbundled-react.min.js:387:4579838)
    at e.createAndProcessError (https://assets.flex.twilio.com/releases/flex-ui/2.10.0/twilio-flex.unbundled-react.min.js:387:4582952)
    at e.handleCoreError [as errorProcessingOverride] (https://assets.flex.twilio.com/releases/flex-ui/2.10.0/twilio-flex.unbundled-react.min.js:387:4581353)
    at e.processError (https://assets.flex.twilio.com/releases/flex-ui/2.10.0/twilio-flex.unbundled-react.min.js:387:9273933)
    at e.createAndProcessError (https://assets.flex.twilio.com/releases/flex-ui/2.10.0/twilio-flex.unbundled-react.min.js:387:9274138)
    at t.componentDidCatch (https://assets.flex.twilio.com/releases/flex-ui/2.10.0/twilio-flex.unbundled-react.min.js:387:9256316)
    at Nh.f.componentDidCatch.c.callback (https://assets.flex.twilio.com/packages/react-dom/17.0.2/react-dom.min.js:142:309)
    at dh (https://assets.flex.twilio.com/packages/react-dom/17.0.2/react-dom.min.js:80:101)
    at Bj (https://assets.flex.twilio.com/packages/react-dom/17.0.2/react-dom.min.js:144:468)
    at Qj (https://assets.flex.twilio.com/packages/react-dom/17.0.2/react-dom.min.js:176:361)
```

### DETAILS
```
{
    "message": "An error has been detected inside DynamicComponent",
    "wrappedError": "Cannot read properties of undefined (reading 'replace')",
    "description": "An error has been detected inside the AgentDesktopView.Panel2 DynamicComponent",
    "context": "DynamicComponent",
    "type": "app",
    "severity": "normal",
    "twilioErrorCode": 45600
}
```

![image](https://github.com/user-attachments/assets/5d0df182-c64d-4410-8a4f-ea81839a0b13)
![task](https://github.com/user-attachments/assets/18cdf876-0b40-4d71-a805-a70f419909b3)
![task2](https://github.com/user-attachments/assets/611fc135-0ff8-4494-b651-ef960ef69a59)
![task3](https://github.com/user-attachments/assets/af2d208a-1e43-4412-a9d0-435f3b749c2e)
![task4](https://github.com/user-attachments/assets/914eb322-e671-4820-abe0-7aa104defb1e)

**Comment by Codewow** [comment]
#64  is the issue for the function code being in the name of the callback task.
